### PR TITLE
headless-gl support changes

### PR DESCRIPTION
**Pull request by ibgreen**
### Excerpt from included changes to 7.1 Upgrade Guide:

Headless gl is no longer automatically used if installed. It needs to be explictly imported by the application:

```bash
yarn install gl
```

```js
import headlessGL from 'gl';
import {createGLContext} from '@luma.gl/core';
const gl = createGLContext({width, height, createNodeContext: headlessGL, ...});
```

This is technically a breaking change however it only affects operation under Node.js. The reason this change was made in a minor realease is that it is getting hard to prevent bundlers like Webpack from bundling headless-gl when bundling for the browser, causing issues for applications.

### CODE REVIEW

**Comment by Pessimistress** [comment]
> it is getting hard to prevent bundlers like Webpack from bundling headless-gl when bundling for the browser

Why can't this be prevented by using the browser field in package.json?

**Comment by tgorkin** [comment]
> > it is getting hard to prevent bundlers like Webpack from bundling headless-gl when bundling for the browser
> 
> Why can't this be prevented by using the browser field in package.json?

I was running into issues trying to build the loaders.gl website, which depends on "@luma.gl/webgl": "^7.0.0".  When trying to generate a production build, I was getting the error:

```
Error: ./node_modules/@luma.gl/webgl/dist/esm/webgl-utils/webgl-types.js
  Module not found: Error: Can't resolve 'gl' in '/Users/tgorkin/Uber/loaders.gl/website/node_modules/@luma.gl/webgl/dist/esm/webgl-utils'
```

I wasn't aware of the browser field feature, but it looks like its present in https://github.com/uber/luma.gl/blob/master/modules/webgl/package.json.  Is there something we need to do on loaders.gl website's package.json as well?  Or is this an issue with ocular-gatsby+webpack not respecting the field?

**Comment by tsaiDavid** [comment]
@shanshanzhu, @ibgreen - do you have any suggestions on what my coworker (@dmi3y) and I might be able to do when using the latest version of `deck.gl`?

When generating production builds of our latest app, we get the same error posted by @tgorkin. However, this is a non issue when we downgrade to `deck.gl@^6.0.0` and `deck.gl@^3.0.0`.

**Comment by ibgreen** [comment]
@tsaiDavid Have you tried actually installing `gl` and rebuilding? That fixed the gatsby build for us.

@tsherif 
- Based on comment there seems to be a difference in how v7 imports `gl` (perhaps `import` vs `require` vs `module.require`). Maybe there is an easy fix?
- If not, should we merge this PR for 7.2? Looks like more people are having bundling problems with `gl`.

**Comment by tsaiDavid** [comment]
@ibgreen - yes we tried, but we're using lerna + yarn workspaces. I tried removing the `yarn.lock` and regenerating it but still having some problems. Will give it another shot and update you

**Comment by tsaiDavid** [comment]
@ibgreen - just tried it again. Although I could build it successfully locally, I'm unable to build it in Zeit's Now platform (which uses Node v8.10, if that matters). I guess for now we will stick with the older versions until we're able to utilize the latest?

```
error /tmp/75dc4b96/node_modules/gl: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /tmp/75dc4b96/node_modules/gl
Output:
prebuild-install WARN install libX11.so.6: cannot open shared object file: No such file or directory
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0
```

**Comment by tsherif** [comment]
Couldn't this use case be handled by creating the context externally?

**Comment by ibgreen** [comment]
> Couldn't this use case be handled by creating the context externally?

Yes it can. We support externally created contexts. We can emphasize this in the docs.

I assume the suggestion is that we could simplify luma.gl by removing support for pre-registering the headless GL context creation function.

That would mean that would have to go through all places where we call `createGLContext` in our test suite and replace with conditional code depending on whether we are in Node or browser.

```js
import createNodeContext from 'gl';
import {setContextDefaults, createGLContext} from '@luma.gl/core';
setContextDefaults({createNodeContext})

// Later in another file
const gl = createGLContext({width, height, ...});
```

**Comment by tsherif** [comment]
I don't really see a reason to add complexity to the architecture when we already have a solution that's more flexible since it isn't coupled to headlessgl or node.

For the test cases, the conditional logic could go into a test utility function in the test suite, e.g. `createTestContext`. Then it would just be a matter of doing a global replace of `createGLContext` with the test version.

**Comment by ibgreen** [comment]
> For the test cases, the conditional logic could go into a test utility function in the test suite, e.g. `createTestContext`

Sure. I haven't double checked, but this breaking change likely does not just affect luma.gl. Additional repos may also be affected. But I suppose they would need to be updated either way, the registration mechanism could make the upgrade a little easier, but not by much.

**Comment by ibgreen** [comment]
@tsaiDavid 	Try 7.1.1 it contains a temporary patch

**Comment by ibgreen** [comment]
I still feel somewhat strongly that we should remove the `m.require('gl')` from luma.gl. We should require the user to explicitly import `gl` and create the headless context outside of luma.gl, and v8.0 would be the time to do this update.

I am not attached to any particular approach, the details of how this would be done is something @tsherif can decide on. 

I will close this PR as it triggered too many questions, but I can help do a new PR based on instructions if desired.

**Comment by tsherif** [comment]
I totally agree. I hoping we can move away from using headlessgl for tests and depend completely on puppeteer, and support the node use case by allowing people to pass in an externally created context. This would also open us up to supporting other node contexts, e.g. https://github.com/google/node-gles

**Comment by ibgreen** [comment]
> I hoping we can move away from using headlessgl for tests and depend completely on puppeteer,

My 2 cents on headless-gl vs puppeteer:

I feel that it is valuable to have a second WebGL implementation to test against, and we'd cast a smaller test net by removing headless gl.

I agree that Puppeteer is convenient, but it is also just another skin on top of Chrome's WebGL implementation. Meaning that it does not provide any additional WebGL platform test coverage, just testing convenience. 

To anticipate the request for use cases, we do have @trxcllnt 's promising work on CUDA integration being done with the non-web based `webgl-raub` environment. That integration worked almost out-of-the-box thanks to the `headless-gl` tests.

That suggests that we could potentially switch our setup from headless-gl to webgl-raub but that is another question.

**Comment by tsherif** [comment]
Superseded by #1298

**Pull request closed without merging**
